on:
  push:
    branches:
    - testing

jobs:
  auto_release:
    name: auto create and push release
    runs-on: ubuntu-22.04
    steps:
      - uses: cachix/install-nix-action@v27

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          branch: testing
          
      - name: Generate Release version from date
        id: date
        run: |
          PKG_NAME="$(basename "${{ github.repository }}" | sed 's/pkg-//g')"
          echo "PKG_NAME=$PKG_NAME" >> $GITHUB_ENV
          TAG_NAME="nightly-$(date +'%Y.%m.%d-%H.%M.%S')"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "Tag name will be: $TAG_NAME"
      
      - name: Generate package.nix
        id: generate_package
        run: |
          sed -i "s/version = \".*\";/version = \"${{ env.TAG_NAME }}\";/g" ./package.nix
          nix build

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.TAG_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          prerelease: true
          files: |
            ./package.nix
